### ISSUE TITLE
about image_sample.py

### ISSUE THREAD

**Issue by fido20160817** [WeilunWang/semantic-diffusion-model#12]
anybody can sample a normal image? this is the sample using image_sample.py and the provided pre-trained model on celeba, anybody knows the reason?
![20230428-215106](https://user-images.githubusercontent.com/21076140/235166348-0d20a39b-62c4-40e0-81a0-7c6eee37761e.png)

**Comment by fido20160817** [comment]
I set wrong parameter values

**Comment by yug125lk** [comment]
> I set wrong parameter values
Hi, which parameters please, I have the same problem.
