### ISSUE TITLE
the performance of ddpm sampling is totally different from that of ddip sampling, reason?

### ISSUE THREAD

**Issue by fido20160817** [WeilunWang/semantic-diffusion-model#14]
group A:
ddpm sampling
![1000_use_ddim_False_0](https://github.com/WeilunWang/semantic-diffusion-model/assets/21076140/2e0bce09-d324-4459-a91d-72cec2a8a81c)

ddim sampling
![1000_use_ddim_True_0](https://github.com/WeilunWang/semantic-diffusion-model/assets/21076140/95bca69b-4672-4503-83ec-df0a26d9e900)

group B:
ddpm sampling
![10017_use_ddim_False_0](https://github.com/WeilunWang/semantic-diffusion-model/assets/21076140/753818f3-7e3a-41ab-a5eb-029f57d2fa8d)

ddim sampling
![10017_use_ddim_True_0](https://github.com/WeilunWang/semantic-diffusion-model/assets/21076140/58c59f2f-a3f5-4e25-8f43-0d6b33af520c)

group C:
ddpm sampling
![10037_use_ddim_False_0](https://github.com/WeilunWang/semantic-diffusion-model/assets/21076140/e0cad97f-1dc7-4441-8197-bc148904faeb)

ddim sampling
![10037_use_ddim_True_0](https://github.com/WeilunWang/semantic-diffusion-model/assets/21076140/a00a6463-b27e-4001-87a1-cccba58cbe7a)

group D:
ddpm sampling
![10045_use_ddim_False_0](https://github.com/WeilunWang/semantic-diffusion-model/assets/21076140/e981bf88-264a-4a37-8c62-3854cc6320fe)

ddim sampling
![10045_use_ddim_True_1](https://github.com/WeilunWang/semantic-diffusion-model/assets/21076140/bd5216fa-56f3-4cea-b80c-9917fcc84e08)

any tips?

**Comment by miquel-espinosa** [comment]
Hi @fido20160817 . Have you figured out a reason? I am not an expert on this, but reading on this [here](https://strikingloo.github.io/wiki/ddim#:~:text=Properties%20of%20DDIM%20vs%20DDPM,have%20similar%20high%2Dlevel%20features.) it seems that DDIM sampling has the property of good latent interpolation between samples, maybe with the trade-off of worse diversity. But I would be happy to know further thoughts on this, if you have any.

Also, may I ask how long did it take you to train the model, and much compute (how many GPUs) did you require? Thanks.

**Comment by fido20160817** [comment]
the training detail is similar to that in guided diffusion. see here for more https://github.com/openai/guided-diffusion/issues/100
