### ISSUE TITLE
Could you tell me how to use Windows to train the Cityscapes dataset?

### ISSUE THREAD

**Issue by ZzzTD** [WeilunWang/semantic-diffusion-model#8]

**Comment by RunRanger** [comment]
Currently trying the same.

I got already some steps:
- install cuda AND cudnn
- install Microsoft MPI v 10.0
- download cityscapes dataset and copy all folders into a data folder
- implement another `th.cuda.is_available()` before initialization, otherwise it takes the cpu...
- change nccl to gloo (nccl is just working on linux) at guided_diffusion>dist_util.py

use following command to run image_train.py:

```
mpiexec -n 1 python image_train.py `
--data_dir D:\MasterJAM\datasets\cityscapes `
--dataset_mode cityscapes `
--lr 1e-4 `
--batch_size 4 `
--attention_resolutions 32,16,8 `
--diffusion_steps 1000 `
--image_size 256 `
--learn_sigma True `
--noise_schedule linear `
--num_channels 256 `
--num_head_channels 64 `
--num_res_blocks 2 `
--resblock_updown True `
--use_fp16 True `
--use_scale_shift_norm True `
--use_checkpoint True `
--num_classes 151 `
--class_cond True `
--no_instance True
```

My current error is now:
`RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.`

**Comment by ZzzTD** [comment]
Thanks a lot,
My current error is now:
RuntimeError: index 23 is out of bounds for dimension 1 with size 19.

**Comment by RunRanger** [comment]
Where/When does the error occure?

Note: I've changed the command parameter -n from 8 to 1

**Comment by ZzzTD** [comment]
> Where/When does the error occure?
> 
> Note: I've changed the command parameter -n from 8 to 1



> Where/When does the error occure?
> 
> Note: I've changed the command parameter -n from 8 to 1

I'm sorry I just saw your answer
Currently, I only modified the number of class to 20, and I am studying how to process Cityscapes datasets the error is:
  File "E:\Pythonfiles\semantic-diffusion-model-main\guided_diffusion\train_util.py", line 275, in preprocess_input
    input_semantics = input_label.scatter_(1, label_map, 1.0)
RuntimeError: index 19 is out of bounds for dimension 1 with size 19

**Comment by bohnedan** [comment]
Hi @ZzzTD just by chance, I received and solved the very same error for a different generative model just yesterday.
You have to dig into the train_util.py and there the function preprocess_input is pulling the number of classes typically from another file (e.g. the dataloader). Adjust these numbers to fit your number of classes/number of RGB codes in your labelId images. e.g. if you have 20 classes, with RGB codes ranging from (0, 0, 0) to (19, 19, 19), then you would specify probably 20 +1 (for unknown) for this variable.

This was the code from the other dataloader (model is also based upon SPADE):
![image](https://user-images.githubusercontent.com/84179792/227139618-27a3e117-88f9-44ad-9525-cb6d5625af5e.png)

As well as the referrence within the models code (probably in train_util.py in your case):
![image](https://user-images.githubusercontent.com/84179792/227139849-b69610ee-af69-42cc-9f72-e507fe8c21b5.png)

**Comment by ZzzTD** [comment]
> Hi @ZzzTD just by chance, I received and solved the very same error for a different generative model just yesterday. You have to dig into the train_util.py and there the function preprocess_input is pulling the number of classes typically from another file (e.g. the dataloader). Adjust these numbers to fit your number of classes/number of RGB codes in your labelId images. e.g. if you have 20 classes, with RGB codes ranging from (0, 0, 0) to (19, 19, 19), then you would specify probably 20 +1 (for unknown) for this variable.
> 
> This was the code from the other dataloader (model is also based upon SPADE): ![image](https://user-images.githubusercontent.com/84179792/227139618-27a3e117-88f9-44ad-9525-cb6d5625af5e.png)
> 
> As well as the referrence within the models code (probably in train_util.py in your case): ![image](https://user-images.githubusercontent.com/84179792/227139849-b69610ee-af69-42cc-9f72-e507fe8c21b5.png)

**Comment by ZzzTD** [comment]
@bohnedan Thank you very much for your careful answer. I'm ready to process Cityscapes for a try. Thank you!!!

**Comment by lzstudent** [comment]
> 
@ZzzTD 
Hi, have you solved the problem? I am also confused about it and can't find why. Thanks.

**Comment by ZzzTD** [comment]
> > 
> 
> @ZzzTD Hi, have you solved the problem? I am also confused about it and can't find why. Thanks.

Hello, I remember I found a solution in SPADE at the time. Please take a look at this project
